# 상품 설명 생성 프롬프트
name: "product_description"
description: "상품 설명을 생성하는 프롬프트"
version: "1.0"

system_prompt: |
  당신은 전문적인 이커머스 콘텐츠 작가입니다.
  주어진 상품 정보를 바탕으로 매력적이고 설득력 있는 상품 설명을 작성해주세요.

user_prompt: |
  상품 정보:
  - 상품명: {product_name}
  - 카테고리: {category}
  - 가격: {price}
  - 주요 특징: {features}
  - 타겟 고객: {target_customer}

  요구사항:
  - {community_tone} 톤으로 작성
  - {emphasis_points} 강조
  - 길이: {content_length}자 이내
  - {additional_requirements}

  위 정보를 바탕으로 상품 설명을 작성해주세요.

output_format: |
  상품 설명은 다음 형식으로 작성해주세요:
  
  [제목]
  {product_name}
  
  [본문]
  {generated_content}
  
  [해시태그]
  {hashtags}

examples:
  - input:
      product_name: "뉴발란스 키즈 패딩"
      category: "아동복"
      price: "89,000원"
      features: "방풍, 방수, 가벼움"
      target_customer: "3-7세 아동"
      community_tone: "친근하고 따뜻한"
      emphasis_points: "품질과 안전성"
      content_length: "500"
      additional_requirements: "계절성 강조"
    output: |
      [제목]
      뉴발란스 키즈 패딩
      
      [본문]
      겨울철 우리 아이를 위한 완벽한 선택! 뉴발란스 키즈 패딩으로 따뜻하고 안전한 겨울을 보내세요. 
      
      방풍과 방수 기능으로 추위와 습기로부터 아이를 보호하며, 가벼운 소재로 활동성을 높였습니다. 
      3-7세 아동에게 최적화된 사이즈와 디자인으로 편안한 착용감을 제공합니다.
      
      [해시태그]
      #뉴발란스 #키즈패딩 #겨울아동복 #방풍방수 #아이패딩
